### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by moetalk** [shanmite/LotteryAutoScript#1]
> (COOKIE格式:DedeUserID=;·SESSDATA=;·bili_jct=;·(点号表示空格 注意顺序与空格要求))

这一段容易引起误会，让人以为只需要这几个值数据，实际上是不只是只有这几值。
另外需要注意的是，获取 cookie 的方法中，如果是在b站网页的 控制台> Console 中输入`document.cookie`，返回的值是不包含`SESSDATA`的

**Comment by shanmite** [comment]
感谢建议
