### ISSUE TITLE
麻烦增加一下自动清理缓存功能

### ISSUE THREAD

**Issue by HIKARuRu1** [shanmite/LotteryAutoScript#11]
每次清理动态后，再清理的时候会提示无法重复删除动态。我想可能是因为之前的本地缓存信息没有被删除，所以会被重复删除。大佬能增加个清理本地缓存的功能吗

**Comment by shanmite** [comment]
指的是云脚本还是油猴脚本

**Comment by HIKARuRu1** [comment]
> 指的是云脚本还是油猴脚本

油猴

**Comment by shanmite** [comment]
清理使用的是什么模式，如果强力删除之后又使用推荐模式就会提示重复删除。

**Comment by HIKARuRu1** [comment]
> 清理使用的是什么模式，如果强力删除之后又使用推荐模式就会提示重复删除。

没，我一直用的推荐模式，还没用过强力删除

**Comment by HIKARuRu1** [comment]
> 清理使用的是什么模式，如果强力删除之后又使用推荐模式就会提示重复删除。

[删除动态]删除动态失败 {"code":500404,"msg":"不能重复删除","message":"不能重复删除","data":{}}
报错是这样的

**Comment by shanmite** [comment]
删的时候选择的是即取关又删动态吗

**Comment by HIKARuRu1** [comment]
> 删的时候选择的是即取关又删动态吗

仅删除动态

**Comment by HIKARuRu1** [comment]
> 删的时候选择的是即取关又删动态吗

我怕同一up之后发过抽奖，取关了就参与不了了

**Comment by shanmite** [comment]
如果不是全选，默认不会清理本地存储

**Comment by shanmite** [comment]
> 如果不是全选，默认不会清理本地存储

我加一个选项上

**Comment by HIKARuRu1** [comment]
> > 如果不是全选，默认不会清理本地存储
> 
> 我加一个选项上

麻烦了
