### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by moetalk** [shanmite/LotteryAutoScript#2]
https://github.com/shanmite/LotteryAutoScript/blob/061f6ee762048c18b0e2e5abd6f32cf56e8a49af/lottery-in-nodejs.js#L18-L19
这两行分别代表什么设置，然后就是值是只有`00`和`01`吗
而且这个 Github Action貌似不支持选择转发官方抽奖还是非官方抽奖

**Comment by shanmite** [comment]
![](https://i.bmp.ovh/imgs/2020/11/041f728158b787da.png)  
以上的0 1分别与这几个单选框对应
