### ISSUE TITLE
请问为什么每次脚本启动时都有这个 服务器拒绝请求？

### ISSUE THREAD

**Issue by 1045925330** [shanmite/LotteryAutoScript#5]
![Screenshot_20201214-110547_Chrome__01](https://user-images.githubusercontent.com/30003970/102039365-85c4f180-3e04-11eb-89d4-67c062ebbf96.png)

另外还有一个问题就是我填了sckey，但是并没有给我推送消息过来

**Comment by shanmite** [comment]
1. `服务器拒绝请求`这个暂时不清楚
2. 中奖了才会推送消息
