### ISSUE TITLE
对于非官方抽奖的一些处理方法小建议

### ISSUE THREAD

**Issue by someash** [shanmite/LotteryAutoScript#51]
我发现脚本会转发一些已经一个月前，并且已经开奖的非官方抽奖，这里建议：
1、在参加非官方抽奖之前先在那个up的动态（置顶评论）寻找是否up自己转发（置顶评论）当前抽奖动态并附带“恭喜”等祝贺中奖的词，如果有就放弃参与那个抽奖。
2、在参加非官方抽奖之后，判断是否中奖时也是一样的方法，并且如果那个转发的动态（置顶的评论）有@xxx用户并且有@自己就推送中奖，如果@的人里没有自己就判断没中；如果没@但是有恭喜就推送那个动态的链接，提醒已经开奖，请自行查看是否中奖

**Comment by shanmite** [comment]
- 转发过就不会转发了，所以刚开始会不稳定，转发过期的抽奖，等运行一段时间后会好一点
- 判断非官方是否中奖用@和私信就够了
