### ISSUE TITLE
脚本运行6个小时后退出并且没有上传到artifact

### ISSUE THREAD

**Issue by someash** [shanmite/LotteryAutoScript#55]
![Screenshot_20210320-081447](https://user-images.githubusercontent.com/32922655/111853091-71891700-8954-11eb-814a-98c86622e874.jpg)
同时，刚刚定时（每3小时一次）的又开始转发已经转发过的抽奖动态

**Comment by shanmite** [comment]
转发太多 运行时间超过了6个小时的上限，被Github强行关闭

**Comment by someash** [comment]
我看你的action也是这样。。。需不需要整个判断时间的功能，时间长了自己停止转发保存等待下一次计划运行
