### ISSUE TITLE
我想问一下，取关和删动态逻辑是怎么样的。

### ISSUE THREAD

**Issue by someash** [shanmite/LotteryAutoScript#56]
我运行Automatic clear dynamic&follow时看它的log描述除了第一页，后面的每页都好像全删掉了？
有点怕它删掉我之前自己转发或发的动态

**Comment by shanmite** [comment]
会跳过开始的两页，然后移出所有的**转发动态**

**Comment by shanmite** [comment]
取关那个临时分区的所有up

**Comment by someash** [comment]
这个逻辑好粗暴啊，这个清除转发我还是disable算了。。。。。

**Comment by shanmite** [comment]
两三个月清一次就够了，有的开奖周期很长

**Comment by someash** [comment]
主要是有些非抽奖转发动态不想被删掉。。。删动态的时候不能改成根据artifact删么

**Comment by someash** [comment]
我觉得对于官方和非官方抽奖的逻辑可以分开来，因为官方抽奖有固定开奖动态和开奖时间，对于官方抽奖可以检测开奖，没中就自动取关删除动态（这个甚至可以写在检测中奖的workflow里），对于非官方还需要斟酌一下。。。
