### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by davidelectricfree** [shanmite/LotteryAutoScript#58]
**MY_CONFIG语法错误**
成功登录
之前无构件
开始参与抽奖
[新建分区]分区新建成功

 [转发动态]成功转发一条动态
[自动关注]失败 尝试切换线路
{"code":22015,"message":"您的账号异常，请稍后再试","ttl":1}
[自动点赞]点赞成功
[自动关注]失败 尝试切换另一条线路
{"code":22015,"msg":"system error","message":"system error","data":[]}
[自动关注]失败
{"code":-400,"message":"请求错误","ttl":1}
写入已转发过的动态信息
开始转发下一组动态
[运行结束]出现异常程序自动关闭

请问一般出现这种是什么情况啊，用的小号，这种情况是不是触发B站的风控了？

另外，还想请教一下，如何本地运行，example.bat弄完，最后依然报错。

**Comment by shanmite** [comment]
账号异常了

**Comment by davidelectricfree** [comment]
> 
> 
> 账号异常了

本地如何部署？我用了你的greenfork脚本，发现那个会有重复转发的情况，这个云端版本本地应该如何用，我看了那个env_example，把cookie写上去，最后按要求运行npm start 还是会报错

**Comment by davidelectricfree** [comment]
> 
> 
> 账号异常了

我担心毕竟action版本不是国内IP，用久了会被风控

**Comment by shanmite** [comment]
提供一下错误日志

**Comment by davidelectricfree** [comment]
> 
> 
> 提供一下错误日志

> npm install && env.bat && node main.js check

audited 136 packages in 2.399s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\david\Documents\GitHub\LotteryAutoScript>_start 鍚姩鑴氭湰
'_start' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>true)
'true)' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>崲鍙傛暟鏃堕』鍏堝皢GlobalVar.json鏂囦欢鍒犻櫎
'崲鍙傛暟鏃堕』鍏堝皢GlobalVar.json鏂囦欢鍒犻櫎' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>苟渚濇鐙珛杩愯
'苟渚濇鐙珛杩愯' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>ATA=xxxxxxxxxxx; bili_jct=xxxxxxx; DedeUserID=xxxxx;
'ATA' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>CLEAR=
'CLEAR' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>true
'true' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>€鐜鍙橀噺(鍙笉濉?
'€鐜鍙橀噺' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SCKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SENDKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_SKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_MODE=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_PUSH=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_SOUND=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_USER_ID=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_HOST=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_PORT=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_SECRET=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QYWX_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set IGOT_PUSH_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_USER=

C:\Users\david\Documents\GitHub\LotteryAutoScript>

**Comment by shanmite** [comment]
字符编码的问题  
运行之前加一句`chcp 65001`

**Comment by davidelectricfree** [comment]
> chcp 65001

C:\Users\david\Documents\GitHub\LotteryAutoScript>run test_check 检查是否中奖(只查看两个小时内的奖)
'run' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>d.txt文件
'd.txt文件' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>复制本项目并依次独立运行
'复制本项目并依次独立运行' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>xxxxxxxxxxx; bili_jct=xxxxxxx; DedeUserID=2078814;
'xxxxxxx' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>REM 推送所需环境变量(可不填)

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SCKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SENDKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_SKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_MODE=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_PUSH=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_SOUND=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_USER_ID=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_HOST=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_PORT=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_SECRET=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QYWX_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set IGOT_PUSH_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_USER=

C:\Users\david\Documents\GitHub\LotteryAutoScript>

**Comment by davidelectricfree** [comment]
> 
> 
> 字符编码的问题
> 运行之前加一句`chcp 65001`

我安装了Npm，并且使用cmd在该项目文件夹下面用指令的，是不是这个项目还有一些其他的环境变量要添加？

**Comment by shanmite** [comment]
命令输错了 `npm run`

**Comment by davidelectricfree** [comment]
> 
> 
> 命令输错了 `npm run`

npm run test_check

> lottery-in-bilibili@2.2.0 test_check C:\Users\david\Documents\GitHub\LotteryAutoScript
> npm install && env.bat && node main.js check

audited 136 packages in 2.336s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\david\Documents\GitHub\LotteryAutoScript>run test_check 检查是否中奖(只查看两个小时内的奖)
'run' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>d.txt文件
'd.txt文件' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>复制本项目并依次独立运行
'复制本项目并依次独立运行' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>xxxxxxx; bili_jct=xxxxxxx; DedeUserID=xxxxxxx;
'xxxxxxxxxxxxx' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\david\Documents\GitHub\LotteryAutoScript>REM 推送所需环境变量(可不填)

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SCKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set SENDKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_SKEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QQ_MODE=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_PUSH=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set BARK_SOUND=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_USER_ID=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_HOST=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set TG_PROXY_PORT=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set DD_BOT_SECRET=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set QYWX_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set IGOT_PUSH_KEY=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_TOKEN=

C:\Users\david\Documents\GitHub\LotteryAutoScript>set PUSH_PLUS_USER=

C:\Users\david\Documents\GitHub\LotteryAutoScript>

**Comment by davidelectricfree** [comment]
> 
> 
> 命令输错了 `npm run`

没有，我之前只是贴了有错误的一部分，我是输的npm run

**Comment by shanmite** [comment]
> 字符编码的问题  
> 运行之前加一句`chcp 65001`
>

**Comment by davidelectricfree** [comment]
> 
> 
> > 字符编码的问题
> > 运行之前加一句`chcp 65001`


上面我在输入命令前，已经在cmd页面输入chcp 65001命令
cmd显示：
Active code page: 65001
然后我再输入npm run test_check

**Comment by shanmite** [comment]
那就把注释全删掉

**Comment by davidelectricfree** [comment]
> 
> 
> 那就把注释全删掉

把所有@echo删掉，运行起来了，因为目前我的账号正在GitHub action跑，它提示cookie错误，但至少证明本地已经进入登录环节了，等我的GitHub action 跑完了我在本地跑一跑完整流程，看是否有问题，十分感谢。
请教一下，本地跑是否有防止重复发动态的功能？

**Comment by shanmite** [comment]
理论上可以

**Comment by davidelectricfree** [comment]
> 
> 
> 理论上可以

谢谢，收到。

**Comment by shanmite** [comment]
换个地方运行，会把之前转过的再重新转一遍，具体可以看一下说明里的防重复转发那部分

**Comment by davidelectricfree** [comment]
> 
> 
> 理论上可以

请教一下，本地关于cookie的格式是什么？我直接把SESSDATA=xxx; bili_jct=xxx; DedeUserID=xxx; 输入进去会出错，把%换成%%也不行

**Comment by davidelectricfree** [comment]
> 
> 
> 换个地方运行，会把之前转过的再重新转一遍，具体可以看一下说明里的防重复转发那部分

好的

**Comment by shanmite** [comment]
退出登录后cookie会失效

**Comment by davidelectricfree** [comment]
> 
> 
> 退出登录后cookie会失效

我没有退出登录，我的浏览器还在界面上挂着。
不管我是给SESSDATA=xxx; bili_jct=xxx; DedeUserID=xxx; 加单引号，还是不加，亦或是把SESSDATA中的三个%换成%%，都提示cookie失效，但是放在GitHub action就可以运行

**Comment by shanmite** [comment]
改设置后删除那个文件没

**Comment by davidelectricfree** [comment]
> 
> 
> 改设置后删除那个文件没
> `GlobalVar.json`

我的失误，删了以后就好了，抱歉

**Comment by davidelectricfree** [comment]
> 改设置后删除那个文件没  
> `GlobalVar.json`

发现有一个bug，就是用cmd运行以后，好像显示一定的数量的操作信息后，就不会继续显示了，虽然软件确实在跑，而且也确实在转发动态，但是在cmd的终端里，不会显示目前在进行的动作。
另外，看方不方便给操作信息加一个时间显示，谢谢。

**Comment by shanmite** [comment]
> 看方不方便给操作信息前加一个时间，能够更加直观一点。

已加

**Comment by davidelectricfree** [comment]
> 
> 
> > 看方不方便给操作信息前加一个时间，能够更加直观一点。
> 
> 已加

谢谢，收到

**Comment by davidelectricfree** [comment]
> 
> 
> > 看方不方便给操作信息前加一个时间，能够更加直观一点。
> 
> 已加

2021/03/26  18:58         1,069,254 002a5672d6157c03e8eb103ad6cfe27fd2825df8.jpg
2021/03/26  18:57         1,160,905 08d3a0ba61d35298324b6492b203ccafcac8e047.jpg
2021/03/26  18:58         1,209,047 100eee48005998e95fa9bac0e73c2f29fd3a4fe1.jpg
2021/03/26  18:57         1,142,570 155a6485cab60923a987403855201681fc0a83f9.jpg
2021/03/26  18:58         1,308,621 1efa08a9b56445b045d841f5a4a4c6ad28933cfc.jpg
2021/03/26  18:58         1,567,798 2adb0ba300e5f7c809f45f6df96f0207754d318a.jpg
2021/03/26  18:58         1,011,829 2b52034f27664084bf1b9a229c553ef46401f820.jpg
2021/03/26  18:58         1,583,274 3534353e19bd183c248f7b8e9d4fb6208c848dc8.jpg
2021/03/26  18:58         1,566,626 41940c665c3dbcb462bea6e045be2f2c23e70e68.jpg
2021/03/26  18:58         1,461,213 41d91578605282d3645fc353a75b402b3578a1d4.jpg
2021/03/26  18:58         1,151,671 49ffbd94db9c9e16232dba762c3b8d577315acfd.jpg
2021/03/26  18:58         1,182,257 505915b9f9f0d0da685fece3e6003cc9edd55429.jpg
2021/03/26  18:58           403,468 535246b85edce9bb98648a48274a221317105f64.jpg
2021/03/26  18:58         1,398,946 586dd9ff2aae422c06609cfe3092c01bf6394b46.jpg
2021/03/26  18:58         1,309,097 5e5f1d8114e09f6974cfedb68c40a5879840b5b7.jpg
2021/03/26  18:58         1,441,715 623e5c3ee9e76b287c2d66c82f26502b6e0c6a2e.jpg
2021/03/26  18:56         1,507,798 685f38aa39a1ab5eaf4539ec93c43dd8b3080d46.jpg
2021/03/26  18:57         1,373,478 691bc2ef16446b53799ecbf8876a3bd9f28a77f2.jpg
2021/03/26  18:58         1,466,181 6fc9cf331465c2752282ef561cca5f437dc0cfe9.jpg
2021/03/26  18:57         1,381,483 72c0e75cb7533d9bf0f9a2f20973d7be3ee5776e.jpg
2021/03/26  18:58           670,869 738f14074bbdbe048c06cdba0d0d7f5a99f04095.jpg
2021/03/26  18:56         1,088,371 7f2992afe48ba626ceb2d7ecbac36716d4f02c62.jpg
2021/03/26  18:57         1,284,407 83904cdf9457e120028cf851353e33749007e048.jpg
2021/03/26  18:58         1,641,795 855dc981138b781eb7173a63a36a8ead28661f1a.jpg
2021/03/26  18:58           180,726 8c11676fc6a328ae8b51dde3511f109ffca3403a.jpg
2021/03/26  18:58         1,583,758 8caef1c882018a3feee9583a110f5ffde708e6e4.jpg
2021/03/26  18:58         1,214,074 8dfb9f526309220cc76d5cd7e6b10e01f801a4bb.jpg
2021/03/26  18:58         1,436,288 9599546697bb36dc64936b364f5c205d7d0e3033.jpg
2021/03/26  18:58         1,387,710 962f991cba2e68d189f011147ae0a4305f815c73.jpg
2021/03/26  18:58         1,363,009 98bd57c84cf376be08b3a617422ac37b9449d762.jpg
2021/03/26  18:58           457,376 99972532ae2f4b631b3be4534fd7959c6f7c21cf.jpg
2021/03/26  18:58           885,265 9d62a2d648624c5274dd38db0c4cade9b50b5bae.jpg
2021/03/26  18:58         1,569,159 a0bea949a684c0019eac14475d93d83568f7dd22.jpg
2021/03/26  18:58           932,280 acec37f12c72a3b03f03caa94b2ec8821e7bcb35.jpg
2021/03/26  18:57         1,120,802 ae0a168e28f085ec560026b7920a7085ed69879b.jpg
2021/03/26  18:58         1,691,970 b5f651623e775f9ac7a1aeb5abafcc6a87b8afc9.jpg
2021/03/26  18:58         1,568,823 b63810a3402c6e87d288bd1bd31b50b814dc5987.jpg
2021/03/26  18:56         1,257,444 b6eaf1fcc69013e5fed5054cedf9a544bbe0532e.jpg
2021/03/26  18:58           245,091 bf568ce407f6d02cb7ff1307532397be77f00fda.jpg
2021/03/26  18:58         1,081,324 d2efdd8d6da1e20422c35157415f4b8f3bccc9cd.jpg
2021/03/26  18:56           488,922 db48485ba5c55bee95e383b90e3710b86404a641.jpg
2021/03/26  18:58         1,036,901 dc33c3586e687200d30a44fe7eeefac7a20c6636.jpg
2021/03/26  18:58         1,630,753 de26caf5bbcfc8456862782369401f1e6f9eb5b4.jpg
2021/03/26  18:56         1,261,186 eb7099a46de3ef5d04f899ad80a62d050012c698.jpg
2021/03/26  18:58           465,956 ee3af145cb04af3a8172724c8dfd113c258c054e.jpg
2021/03/26  18:56         1,466,388 eeae2cdc4daedd77b509c6a968325255ab61d785.jpg
2021/03/26  18:58         1,196,594 ef6bf0dd4e03d1d5c2afd7fc7bcc410e33201030.jpg
2021/03/26  18:58         1,107,676 f47b3bb9575a8c9514b323368abdcc0554e8e21a.jpg
2021/03/26  18:58         1,333,903 f4b9e1bb90f5237424036835fef5a18c13624bd8.jpg
2021/03/26  18:58           896,592 f76e72d4524a31a3c3408770d0b69d2922069945.jpg

上面是https://gitee.com/shanmite/lottery-notice/raw/master/pictures.json中有效的图片。其他没有列出的似乎已经无效了。

**Comment by shanmite** [comment]
的确
`str.match(/(.*\n)/g).map(it => 'https://i0.hdslb.com/bfs/album/'+it.slice(-45))`  
就用你这些了

**Comment by davidelectricfree** [comment]
> 
> 
> 的确
> `str.match(/(.*\n)/g).map(it => 'https://i0.hdslb.com/bfs/album/'+it.slice(-45,-1))`
> 就用你这些了

十分感谢。

**Comment by davidelectricfree** [comment]
> 
> 
> 的确
> `str.match(/(.*\n)/g).map(it => 'https://i0.hdslb.com/bfs/album/'+it.slice(-45,-1))`
> 就用你这些了

https://github.com/xCss/bing

如果缺少图片的话，看可不可以用这个项目的，全是bing的每日图片，API自己就支持随机。

**Comment by davidelectricfree** [comment]
> 
> 
> 的确
> `str.match(/(.*\n)/g).map(it => 'https://i0.hdslb.com/bfs/album/'+it.slice(-45,-1))`
> 就用你这些了

看有没有可能把图片来源换成那种稳定的API，这样图样能更多一些。比如说：https://source.unsplash.com/
