### ISSUE TITLE
有时会评论失败

### ISSUE THREAD

**Issue by jimodeniuren** [shanmite/LotteryAutoScript#6]
![](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//%E8%AF%84%E8%AE%BA%E5%A4%B1%E8%B4%A5.jpg)

自动评论有时会失败，然后程序就退出运行了，不知道是什么原因？

**Comment by shanmite** [comment]
短时间内评论次数过多会被要求回答社区规范，然后才能继续评论，没有回答就会被拒绝，也就是“评论失败” ，所以我设置了一个出现错误立即中止
