### ISSUE TITLE
运行了30s就结束了，出现了警告

### ISSUE THREAD

**Issue by lotterydraw2** [shanmite/LotteryAutoScript#61]
lottery_4No files were found with the provided path: lib/dyid.txt. No artifacts will be uploaded.
--
lottery_5No files were found with the provided path: lib/dyid.txt. No artifacts will be uploaded.
lottery_2No files were found with the provided path: lib/dyid.txt. No artifacts will be uploaded.
lottery_3No files were found with the provided path: lib/dyid.txt. No artifacts will be uploaded.

**Comment by shanmite** [comment]
这个“警告”是说没有构件上传，因为没有运行  
jobs里面才是日志，可以看看

**Comment by chaixin25** [comment]
> 这个“警告”是说没有构件上传，因为没有运行
> jobs里面才是日志，可以看看

![image](https://user-images.githubusercontent.com/43713385/112744772-88271200-8fd5-11eb-9c43-b43b23c80cb6.png)

**Comment by chaixin25** [comment]
是哪里我没设置好吗

**Comment by shanmite** [comment]
run in nodejs里面

**Comment by chaixin25** [comment]
![image](https://user-images.githubusercontent.com/43713385/112744884-785bfd80-8fd6-11eb-821f-928cea2a1fbd.png)

**Comment by shanmite** [comment]
cookies填错了

**Comment by chaixin25** [comment]
需要填DedeUserID=***;SESSDATA=***;bili_jct=***这种格式还是直接填内容

**Comment by shanmite** [comment]
按照readme要求填写
