### ISSUE TITLE
运行清理动态任务超时报错

### ISSUE THREAD

**Issue by Eric-zzzZ** [shanmite/LotteryAutoScript#64]
提示我超过360分钟  
<img width="554" alt="微信截图_20210404201736" src="https://user-images.githubusercontent.com/70245823/113508641-c1d2bc80-9583-11eb-9156-a47ff065a671.png">
<img width="607" alt="微信截图_20210404202237" src="https://user-images.githubusercontent.com/70245823/113508644-c4351680-9583-11eb-9d29-45fc9c02f386.png">

**Comment by shanmite** [comment]
github的限制，所以最好在本地运行
