### ISSUE TITLE
关于中奖通知的一些建议

### ISSUE THREAD

**Issue by 888haobing** [shanmite/LotteryAutoScript#65]
**可不可以添加发送到邮箱的通知方式？**
####大概只需要添加4个密钥，1发件服务器（类似于smtp.yandex.com/smtp.163.com等），2用户名，3密码或类似于授权码（163/qq等），4收件邮箱
p.s.如果能够把转发的运行结果也一起发过来就更好了，还有关于用github action发邮件，action的docs了有试例。

#最后，谢谢大佬了!( ´͈ ⌵ `͈ )σண♡﻿

**Comment by shanmite** [comment]
**邮件推送已添加**
转发的运行结果没必要发，想看的时候登录GitHub看就行了

**Comment by xiaoming140** [comment]
可以不自己发自己吗？我有一个专门的发件域名邮箱，而且拿授权码好麻烦啊

**Comment by shanmite** [comment]
改了

**Comment by shanmite** [comment]
改了
