### ISSUE TITLE
中奖逻辑判定时间与通知

### ISSUE THREAD

**Issue by davidelectricfree** [shanmite/LotteryAutoScript#67]
程序的逻辑是判定@（含有中奖关键词）的时间是否在两小时以内，如果在，则进行通知，但如果程序没有在GitHub上跑，也就是没有每两个小时运行一次的话，是否就会出现，实际中奖，但是超过2小时，程序认为没中的情况。
如果程序在本地运行的话，看作者是否方便将这个判定时间，让用户通过自定义文件来修改。

另外补充一点。
看到作者更新了邮箱，这个功能很棒，第一时间就用上了。
作者忘记更新example.bat了。

**Comment by shanmite** [comment]
`lib/lottery-in-nodejs.js`文件里可以修改时间（两处）

**Comment by davidelectricfree** [comment]
> 
> 
> `lib/lottery-in-nodejs.js`文件里可以修改时间（两处）

好的，这样比较麻烦的是，每次你更新程序之后，我都要修改源文件

**Comment by shanmite** [comment]
添加了快捷方法，更新后看看`env.example.bat`文件

**Comment by davidelectricfree** [comment]
> 
> 
> 添加了快捷方法，更新后看看`env.example.bat`文件

谢谢
