### ISSUE TITLE
# 防重复转发失效，已经授权令牌和创建PAT填入。

### ISSUE THREAD

**Issue by nightmare-mio** [shanmite/LotteryAutoScript#70]
* 同一个动态抽奖仍然转发了好几次。比如3点运行转发一次，action下一次运行仍然会转发同一条动态抽奖

**Comment by nightmare-mio** [comment]
什么是构件，我不能理解，不太懂。

**Comment by shanmite** [comment]
> * 同一个动态抽奖仍然转发了好几次。比如3点运行转发一次，action下一次运行仍然会转发同一条动态抽奖

理论上不会重复转发，没找到原因但对中奖没有影响

**Comment by shanmite** [comment]
> 什么是构件，我不能理解，不太懂。

程序运行中产生的文件  
在每一条工作流里面可以看到

**Comment by nightmare-mio** [comment]
假如A发布抽奖动态，B和C转发，那么会转发ABC三人的动态算一个动态吗？

**Comment by nightmare-mio** [comment]
就像这样转发的是同一个抽奖，但是还是有细微的差别的。
![1](https://user-images.githubusercontent.com/52735303/114335930-6fdff700-9b80-11eb-86a1-67c58acb4994.jpg)
![2](https://user-images.githubusercontent.com/52735303/114335932-71a9ba80-9b80-11eb-911b-946c3a1af686.jpg)

**Comment by shanmite** [comment]
这种属于加码抽奖

**Comment by shanmite** [comment]
> 就像这样转发的是同一个抽奖，但是还是有细微的差别的。
> ![1](https://user-images.githubusercontent.com/52735303/114335930-6fdff700-9b80-11eb-86a1-67c58acb4994.jpg)
> ![2](https://user-images.githubusercontent.com/52735303/114335932-71a9ba80-9b80-11eb-911b-946c3a1af686.jpg)
> 

这种是加码抽奖

**Comment by nightmare-mio** [comment]
就是说并不是重复转发？
