### ISSUE TITLE
一个question

### ISSUE THREAD

**Issue by handsomebubu** [shanmite/LotteryAutoScript#72]
取关分区
clear_partition

抽奖UP用户分组id
partition_id

自动action 这个2个设置的用处没明白：
一、取关分区clear_partition的意义没搞懂，需要单独弄个分组来取关？
取关逻辑不是从抽奖up分组里面去删动态并取关嘛 ，对于在其他分组的up仅删除动态不取关。

二、partition_id默认设置id是0,那不就全部存在默认分组里了吗？
如果设置成一个固定的名字，但是不同用户的用户组id是不一样的，多用户这样似乎搞不定。

**Comment by shanmite** [comment]
> 取关分区
> clear_partition

默认就是那个临时分组，但是可以自定义，可以选择清理其他分区  

> 抽奖UP用户分组id
> partition_id

因为获取分组ID极易频繁，而分组ID是不会变的，所以可以将其直接存起来，这个字段只有填了且不为空不为0才会起效

**Comment by handsomebubu** [comment]
> > 取关分区
> > clear_partition
> 
> 默认就是那个临时分组，但是可以自定义，可以选择清理其他分区
> 
> > 抽奖UP用户分组id
> > partition_id
> 
> 因为获取分组ID极易频繁，而分组ID是不会变的，所以可以将其直接存起来，这个字段只有填了且不为空不为0才会起效

clear_partition那就必须要配合自定义分区才有意义，现在这个设置没啥意义呢，config里面有没有都无伤大雅。或者干脆设置一个抽奖up组，把中奖的up放另外一个组，没中奖的就如同现在的设置 从抽奖up里面删动态取关

**_partition_id这个对于多用户有问题，同一个人分组id是不变的 ，但是不同人的分组id是不一样，如果定义了一个组id，其他人的就会出错吧_**

**Comment by shanmite** [comment]
也可以不用管，主要是在本地运行时使用

**Comment by handsomebubu** [comment]
> 也可以不用管，主要是在本地运行时使用

怕频繁只要把时间间隔调长点就好了 ，一天运行1-2次就不要频发了
