### ISSUE TITLE
看可不可以将故意利用关键词进行转发抽奖的UP主自动拉黑

### ISSUE THREAD

**Issue by davidelectricfree** [shanmite/LotteryAutoScript#77]
![图片](https://user-images.githubusercontent.com/36690822/116337457-b71ae880-a80c-11eb-8a65-9d14e2dff48d.png)

如上图，这种UP主很多，我之前手动加黑名单两个，但是今天发现我关注的人有好几个这样的，而且这些UP主背后都是同一个人/公司运营的，就是利用关键词来故意吸粉，有的账号还带有闪电标签，不过这些人也有一个共同点，他们的个人简介那里都有：需要视频配资料+lezijie 这样的关键词，
如图：
1.
![图片](https://user-images.githubusercontent.com/36690822/116337897-72dc1800-a80d-11eb-8490-c6afb11906f1.png)
2.
![图片](https://user-images.githubusercontent.com/36690822/116337923-7e2f4380-a80d-11eb-883d-f8352e043784.png)
3.
![图片](https://user-images.githubusercontent.com/36690822/116338035-b5055980-a80d-11eb-83b5-46659b28a7d8.png)

看可不可以把【lezijie】和其他这些简介通用的词作为关键词，进行自动识别，发现有这种关键词的自动加黑。

https://search.bilibili.com/all?keyword=lezijie&from_source=web_search&page=11

随便搜索了一下，就一个页面就有十几个完全不同的账号，我估计这个公司应该不止十几个账号，手动拉黑实在麻烦，如果有自动的功能会好很多。（自动识别简介的关键词，进行拉黑，如果这个关键词能够放到my_config里面就更好了）

**Comment by shanmite** [comment]
有关键词黑名单功能

**Comment by davidelectricfree** [comment]
> 
> 
> 有关键词黑名单功能

我试试吧，主要是他转发的那些关键词都是大范围的，什么程序员这样的，感觉针对性还差点

**Comment by davidelectricfree** [comment]
> 
> 
> 有关键词黑名单功能

用Python写了个小程序，把它所有的UID识别了一下，有七十多个UID，无语了，主要是你这个项目不是 py 的，如果是py的我就直接提交 pr 了。

**Comment by shanmite** [comment]
可以把黑名单提交到[这里](https://gitee.com/shanmite/lottery-notice/blob/master/update_black_list.js)，一次只能提交一个，提交多个需要改下代码

**Comment by davidelectricfree** [comment]
> 
> 
> 可以把黑名单提交到[这里](https://gitee.com/shanmite/lottery-notice/blob/master/update_black_list.js)，一次只能提交一个，提交多个需要改下代码

没咋玩过 JS ，你这边直接改到你的云端仓库吧，已经是合并后的版本了。

292012346,1309889741,307235857,590719194,1255139104,454194576,1613095934,1360529881,1149728866,1884437525,389766233,66810822,2073948621,2039489053,677809149,1968531074,206573406,2027628180,1621946465,1779402209,396901800,1001395107,698327474,2072305049,505965036,1197404658,1789678296,1893912384,11039183,399413444,2137453093,570120249,405578210,1466145116,1254357775,1654092910,688227985,1546106778,587863497,613568254,298494710,1070178590,513310855,432381750,188547207,698597053,224823796,206928336,121457673,1512081233,494265465,1887360476,699208028,391504150,96060277,1537253870,688200318,206573488,1896127915,1714132689,1747553925,697620935,1285823917,1431365587,1977740217,690747829,1828530135,2143477023,586721688,1738297185,417005409,392021547,28008897,28272016,140389827,24598781,28008860,28008880,28008743,28008948,28009292,319696958,90138218,28272000,28272047,28271978,8831288,175979009,3177443,486780865,403048135,474325039,455274996,477519424,292671666,448873224,22498938,1770865,444796995,306112375,320193786,606637517,305276429,204487541,404761800,186914127,99439379,457697569,270886929,401575,201296348,206804212,333584926,34679178,699923691,392689522,178700744,272882445,350977368,487168411,22682842,444949061,523974463,192231907,503908324,383189098,252909207,336467750,264875137,90721742,452299642,677739290,441522918,8766623,5439672,483247863,237055308,95404163,202052696,627942060,455030741,406353670,18036870,470220612,1346052604,501312931

**Comment by davidelectricfree** [comment]
> 
> 
> 可以把黑名单提交到[这里](https://gitee.com/shanmite/lottery-notice/blob/master/update_black_list.js)，一次只能提交一个，提交多个需要改下代码

忘了说了，这个版本可能和你的远端仓库还有一点区别，你可能要去一下重，可能有一些你的远端仓库版本有的，这里面没有。

**Comment by shanmite** [comment]
这个是一次提交多个的脚本  
格式：逗号分割的字符串（末尾不加逗号）  
会自动去重

```js
(function(uid) {

    if (!uid) {
        alert('无效输入');
        return
    }

    $.get('/slice30k/base64-js/raw/master/base64.js').done(basecode => {

        eval(basecode)

        $.get('/api/v5/repos/shanmite/lottery-notice/contents/notice.json').done(notice => {

            (function(content) {

                content.config.blacklist = Array.from(new Set([...content.config.blacklist.split(','), uid.split(','))])).toString();

                content = window.BASE64.encode(JSON.stringify(content));

                $.ajax({

                    url: '/api/v5/repos/shanmite/lottery-notice/contents/notice.json',

                    method: 'PUT',

                    data: {

                        access_token: 'df59f9ec7a8c1695de4b6d3b222a03f0',

                        content,

                        sha: notice.sha,

                        message: uid,

                    }

                }).done(res => {
                    if (res.commit) {
                        alert('提交成功')
                    } else {
                        alert('提交失败')
                    }
                })

            })(JSON.parse(window.BASE64.decode(notice.content)))

        })

    })

})(prompt('填入uid', ''))
```

**Comment by davidelectricfree** [comment]
> 这个是一次提交多个的脚本  
> 格式：逗号分割的字符串（末尾不加逗号）  
> 会自动去重
> 
> ```js
> (function(uid) {
> 
>     if (!uid) {
>         alert('无效输入');
>         return
>     }
> 
>     $.get('/slice30k/base64-js/raw/master/base64.js').done(basecode => {
> 
>         eval(basecode)
> 
>         $.get('/api/v5/repos/shanmite/lottery-notice/contents/notice.json').done(notice => {
> 
>             (function(content) {
> 
>                 content.config.blacklist = Array.from(new Set([...content.config.blacklist.split(','), uid.split(','))])).toString();
> 
>                 content = window.BASE64.encode(JSON.stringify(content));
> 
>                 $.ajax({
> 
>                     url: '/api/v5/repos/shanmite/lottery-notice/contents/notice.json',
> 
>                     method: 'PUT',
> 
>                     data: {
> 
>                         access_token: 'df59f9ec7a8c1695de4b6d3b222a03f0',
> 
>                         content,
> 
>                         sha: notice.sha,
> 
>                         message: uid,
> 
>                     }
> 
>                 }).done(res => {
>                     if (res.commit) {
>                         alert('提交成功')
>                     } else {
>                         alert('提交失败')
>                     }
>                 })
> 
>             })(JSON.parse(window.BASE64.decode(notice.content)))
> 
>         })
> 
>     })
> 
> })(prompt('填入uid', ''))
> ```

浏览器控制台直接复制粘贴用吗？还是怎么用？

**Comment by shanmite** [comment]
控制台粘贴回车

**Comment by davidelectricfree** [comment]
> 控制台粘贴回车

ok，到时候拿到电脑了我上传一下

**Comment by davidelectricfree** [comment]
> 
> 
> 控制台粘贴回车

Uncaught SyntaxError: missing ] after element list
note: [ opened at line 16, column 62

**Comment by shanmite** [comment]
算了，你把要提交的黑名单给我，我有空加上去

**Comment by davidelectricfree** [comment]
> 算了，你把要提交的黑名单给我，我有空加上去

就是上面的

**Comment by shanmite** [comment]
OK :)
