### ISSUE TITLE
本地运行无法获取my_config.json设置

### ISSUE THREAD

**Issue by handsomebubu** [shanmite/LotteryAutoScript#83]
在win服务器上运行时，试过了放在项目文件夹下 &项目跟目录下 &盘跟目录下 运行都提示无自定义设置
![QQ图片20210502182520](https://user-images.githubusercontent.com/37483901/116809988-c8992300-ab73-11eb-8faf-b198f037a0a4.png)
![QQ图片20210502182954](https://user-images.githubusercontent.com/37483901/116810128-77d5fa00-ab74-11eb-8a6d-3cf07dd00f26.png)
![QQ图片20210502182958](https://user-images.githubusercontent.com/37483901/116810130-79072700-ab74-11eb-8515-a0c405018b59.png)
![QQ图片20210502183006](https://user-images.githubusercontent.com/37483901/116810131-799fbd80-ab74-11eb-9a88-9e6b3bf9364e.png)
![QQ图片20210502183010](https://user-images.githubusercontent.com/37483901/116810132-799fbd80-ab74-11eb-8bc5-d7d24872d335.png)

**Comment by shanmite** [comment]
文件内容是否有语法错误(JSON格式)

**Comment by handsomebubu** [comment]
> 文件内容是否有语法错误(JSON格式)

是从在线action里面复制进来的  ，仅仅添加了注释，本地是不是注释都要删掉才行？

**Comment by shanmite** [comment]
json格式不允许有注释

**Comment by shanmite** [comment]
#62 添加了注意事项
