### ISSUE TITLE
获取粉丝数出错,可能是访问过频繁

### ISSUE THREAD

**Issue by earlymengli** [shanmite/LotteryAutoScript#84]
2021/5/3 上午11:34:23: 成功登录
2021/5/3 上午11:34:23: 开始参与抽奖
2021/5/3 上午11:34:23: [获取关注列表]成功
2021/5/3 上午11:34:23: 开始获取用户15363359的动态信息
2021/5/3 上午11:34:23: 准备读取3页动态
2021/5/3 上午11:34:23: 正在读取其中第1页动态
2021/5/3 上午11:34:24: 开始读取第2页动态信息
2021/5/3 上午11:34:24: 正在读取其中第2页动态
2021/5/3 上午11:34:24: 开始读取第3页动态信息
2021/5/3 上午11:34:25: 正在读取其中第3页动态
2021/5/3 上午11:34:25: 3页信息全部成功读取完成
2021/5/3 上午11:34:26: 成功获取用户15363359的动态信息
2021/5/3 上午11:34:26: 无未转发抽奖
2021/5/3 上午11:34:26: [获取关注列表]成功
2021/5/3 上午11:34:26: 开始获取用户31252386的动态信息
2021/5/3 上午11:34:26: 准备读取3页动态
2021/5/3 上午11:34:26: 正在读取其中第1页动态
2021/5/3 上午11:34:26: 开始读取第2页动态信息
2021/5/3 上午11:34:27: 正在读取其中第2页动态
2021/5/3 上午11:34:27: 开始读取第3页动态信息
2021/5/3 上午11:34:28: 正在读取其中第3页动态
2021/5/3 上午11:34:28: 3页信息全部成功读取完成
2021/5/3 上午11:34:28: 成功获取用户31252386的动态信息
2021/5/3 上午11:34:28: 无未转发抽奖
2021/5/3 上午11:34:28: [获取关注列表]成功
2021/5/3 上午11:34:28: 开始获取用户80158015的动态信息
2021/5/3 上午11:34:28: 准备读取3页动态
2021/5/3 上午11:34:28: 正在读取其中第1页动态
2021/5/3 上午11:34:29: 开始读取第2页动态信息
2021/5/3 上午11:34:29: 正在读取其中第2页动态
2021/5/3 上午11:34:29: 开始读取第3页动态信息
2021/5/3 上午11:34:30: 正在读取其中第3页动态
2021/5/3 上午11:34:30: 3页信息全部成功读取完成
2021/5/3 上午11:34:31: 成功获取用户80158015的动态信息
2021/5/3 上午11:34:31: [获取粉丝数]尝试切换线路
2021/5/3 上午11:34:31: 获取粉丝数出错,可能是访问过频繁
[响应错误]HTTP状态码: 412 响应数据:
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}
2021/5/3 上午11:34:31: 准备创建一条随机动态
2021/5/3 上午11:34:31: 准备读取1页动态
2021/5/3 上午11:34:31: 正在读取其中第1页动态
2021/5/3 上午11:34:31: 1页信息全部成功读取完成
2021/5/3 上午11:34:31: 已有一条非转发动态故无需创建
2021/5/3 上午11:34:31: [运行结束]程序自动关闭

**Comment by earlymengli** [comment]
请问大佬 这是什么问题

**Comment by shanmite** [comment]
请求频繁了，IP被禁止访问，降低一下操作频率
