### ISSUE TITLE
无法从构件获取已转发动态了

### ISSUE THREAD

**Issue by handsomebubu** [shanmite/LotteryAutoScript#89]
无法从构件获取已转发动态了，单用户版的当时可以顺利获取。

![QQ图片20210513013154](https://user-images.githubusercontent.com/37483901/118028770-0a0ca800-b396-11eb-8e2a-72d8fd78744e.png)
![QQ图片20210513025236](https://user-images.githubusercontent.com/37483901/118029001-4b9d5300-b396-11eb-9f27-73f169026e68.png)

**Comment by shanmite** [comment]
如果是本地运行，可以不填那两项，也就不用获取构件，构件是actions运行防重复所必须的

**Comment by handsomebubu** [comment]
> 如果是本地运行，可以不填那两项，也就不用获取构件，构件是actions运行防重复所必须的

本地运行的话 ，如果没这个dyid 还是会重复转发的

**Comment by shanmite** [comment]
lib目录下是否有生成了对应的dyid文件，文件内容？

**Comment by handsomebubu** [comment]
> lib目录下是否有生成了对应的dyid文件，文件内容？

生成的只是最新转发的，对已经转发的没有记录，所以还是会重复转发不是吗？

**Comment by shanmite** [comment]
没有记录？不是以追加的方式写入文件的吗

**Comment by handsomebubu** [comment]
算了下 ，只是写入了 新转发的 ，以前已经转发的没有记录进去。
