### ISSUE TITLE
关于服务器运行转发的动态重复

### ISSUE THREAD

**Issue by mama2100** [shanmite/LotteryAutoScript#92]
使用ubuntu服务器运行定时任务转发的动态重复，需要如何设置

**Comment by mama2100** [comment]
看到其中的`PAT` 与 `GITHUB_REPOSITORY` 两项是为了从构件中下载已转发信息 可不填，是否需要填写这两个字段，他们的值该从何获取

**Comment by shanmite** [comment]
重复情况？  
提供一下重复动态截图，间隔时间

**Comment by mama2100** [comment]
![b2](https://user-images.githubusercontent.com/50139256/118441907-7122b780-b71c-11eb-97b1-983518f29b88.PNG)
![不](https://user-images.githubusercontent.com/50139256/118441909-72ec7b00-b71c-11eb-9972-4cc3ef4d17a6.PNG)

**Comment by shanmite** [comment]
每条动态都重复两次吗
是否已同步到最新版本
是否有自定义设置，设置截个图

**Comment by mama2100** [comment]
好像并不是每一条，版本为最新的
env.js信息如下：
![Uploading 1.1.PNG…]()

**Comment by mama2100** [comment]
![1 1](https://user-images.githubusercontent.com/50139256/118443519-90224900-b71e-11eb-818a-04fbc6cf1874.PNG)

**Comment by shanmite** [comment]
了解了，可能有bug，lib目录下有dyid. txt文件，里面储存有已转发的动态ID，你看一下重复动态是否在里面

**Comment by mama2100** [comment]
好的，收到，谢谢大佬
