### ISSUE TITLE
想加之前你那个1078开头的交流群

### ISSUE THREAD

**Issue by davidelectricfree** [shanmite/LotteryAutoScript#95]
**其他**  
想加之前你那个1078开头的交流群，但是发现搜索不到了，现在还有这种能够加入的交流群吗 @shanmite

**Comment by shanmite** [comment]
群还在，只是闭群了，怎么现在想起加群

**Comment by davidelectricfree** [comment]
> 
> 
> 群还在，只是闭群了，怎么现在想起加群

因为看到你的GreasyFork 脚本的通知了，而且你把那个脚本都隐藏了，这个群号还是我从网页缓存搞到的

**Comment by shanmite** [comment]
行吧，群暂时开放一会，可以进来
密 2233

**Comment by lintao140** [comment]
我也想进
