### ISSUE TITLE
更新ck后，部分账号不进行转发了

### ISSUE THREAD

**Issue by handsomebubu** [shanmite/LotteryAutoScript#97]
最开始3个账号都能按照计划任务正常运行，后来2个号的CK过期后 ，更新了ck。然后问题出现了，第二个号隔了一天才开始转发，第3个号一直没有转发。

手动运行3个账号都会进行转发 ，计划任务是按照给出的教程来设置是 ，以前能按照计划任务到点转发，自从有ck过期更换了新ck后，就出现计划任务运行后账号不完全转发的问题了。

昨天删除了所有文件只留了config。json 和evn.js  其他文件重新进行解压 ，今天看结果依旧是第三个账号不转发，计划任务已经正常运行了

**使用环境:**  
 - 服务器运行win12

![QQ图片20210528133622](https://user-images.githubusercontent.com/37483901/119935233-bdda7e00-bfb9-11eb-86da-d2d3c6691976.png)

**Comment by shanmite** [comment]
提供一下计划任务的详细配置

**Comment by handsomebubu** [comment]
电源那里我试了好几种  ，但无论勾不勾选电池电源，没差别
![QQ图片20210528162500](https://user-images.githubusercontent.com/37483901/119954175-503a4c00-bfd1-11eb-8cf8-8dec2e5844d6.png)
![QQ图片20210528162455](https://user-images.githubusercontent.com/37483901/119954204-56c8c380-bfd1-11eb-8aea-86a882dbef1c.png)
![QQ图片20210528162449](https://user-images.githubusercontent.com/37483901/119954220-5af4e100-bfd1-11eb-9e1f-72c2f30f0bff.png)
![QQ图片20210528162444](https://user-images.githubusercontent.com/37483901/119954235-5d573b00-bfd1-11eb-8ac8-49962c2df0ea.png)
![QQ图片20210528162438](https://user-images.githubusercontent.com/37483901/119954252-60522b80-bfd1-11eb-910c-efd42ee96287.png)

**Comment by handsomebubu** [comment]
> 提供一下计划任务的详细配置
刚刚又看了下  ，这回就第一个号运行了，第二个 第三个号 都没转发动态了
